### PR TITLE
fix #2762

### LINKED ISSUE #2762: 404 when using dynamic routing
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

## Description
It will bring 404 problem when using dynamic routing(*,:) like below , by calling http://localhost:8080/all. It seemed can not match the path with prefix 'a', such as 'all'.

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()

	r.GET("/aa/*xx", newHandler("/aa/*xx"))
	r.GET("/ab/*xx", newHandler("/ab/*xx"))
	r.GET("/:cc", newHandler("/:cc"))

	r.Run() // listen and serve on 0.0.0.0:8080 
}

func newHandler(t string) func(c *gin.Context) {
	return func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": t,
		})
	}
}
```

## Expectations

```
$ curl http://localhost:8080/all
/:cc
```

## Actual result

```
$ curl http://localhost:8080/all
404 page not found
```

## Environment

- go version:
- gin version (or commit ref): 1.7.2
- operating system:

### PR DESCRIPTION
**Pull request by qm012**
#### content

* handle level 1 router match
* It does not affect the matching of the following routes
* level1 router match Will cause params to fail
```
file: tree.test
line: 198 199
new PR handle
```

### CODE REVIEW

**Comment by qm012** [comment]
Detailed content： #2762

**Comment by qm012** [comment]
@appleboy @rw-access  Would you please take a look when you are free? Very thx. 😃

File: tree.go [hunk 1]
```diff
@@ -405,11 +406,30 @@ type nodeValue struct {
 // made if a handle exists with an extra (without the) trailing slash for the
 // given path.
 func (n *node) getValue(path string, params *Params, unescape bool) (value nodeValue) {
-	var skipped *skip
+	var (
+		skipped *skip
+		nroot   = &(*n)                                // not found `level 1 router` use nroot
+		ldi     = len(strings.Split(path, "/")[1]) + 1 // level 1 router '/' index
+		ri      int                                    //record index
```
Comment (rw-access) [inline tree.go:413]: these names are a little too short and cryptic for my taste. mind making them longer? (i.e. `recordIndex`)

**Review by rw-access — COMMENTED** [review]
can you add some more comments and/or an explanation of how this works? it's not clear what's going on and that makes it hard to review

File: .gitignore [hunk 2]
```diff
@@ -5,3 +5,4 @@ count.out
 test
 profile.out
 tmp.out
+.idea
```
Comment (appleboy) [inline .gitignore:8]: revert this.

**Review by appleboy — CHANGES_REQUESTED** [review]

File: tree.go (hunk 1 above)
Comment (qm012) [reply tree.go]: thanks for your review, more comments have been added.

File: .gitignore (hunk 2 above)
Comment (qm012) [reply .gitignore]: thanks for your review,has been reset,can you tell me why? please I'll remember (same file: .vscode)

**Comment by appleboy** [comment]
Please also add benchmark result like https://github.com/gin-gonic/gin/pull/2706#issuecomment-828915618 comment.

**Comment by qm012** [comment]
> Please also add benchmark result like [#2706 (comment)](https://github.com/gin-gonic/gin/pull/2706#issuecomment-828915618) comment.

hi，local 'go test' passed and add benchmark if there are omissions, please help me to add. 😆

The previous code could not match when running 'benchmark', and 404 not found occurred,so I fix the code.😆

The benchmarks:

**this PR** - https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231071258

The `benchstat` report:

```shell
BenchmarkGin_Param        	53810290	        68.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	24983499	       144 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 8174235	       432 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	27743445	       129 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	28786916	       125 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	15244320	       236 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubAll    	   83005	     43175 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusStatic  	43877554	        82.3 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusParam   	31455780	       114 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlus2Params 	23434296	       154 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusAll     	 2101560	      1695 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseStatic  	44035694	        81.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseParam   	43929930	        82.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Parse2Params 	34703761	       104 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseAll     	 1215774	      2948 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_StaticAll    	   97797	     36469 ns/op	       0 B/op	       0 allocs/op
```

Thank you all for your reviews.

**Comment by qm012** [comment]
**this PR Benchmark** https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231163846
commit: [4e8e2cb](https://github.com/qm012/gin/tree/develop-2762)

```shell
goos: linux
goarch: amd64
pkg: github.com/julienschmidt/go-http-routing-benchmark
BenchmarkGin_Param        	54527260	        66.8 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	25176636	       143 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 8204526	       431 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	28036678	       128 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	29023458	       126 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	15394497	       233 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubAll    	   84313	     42196 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusStatic  	44162476	        83.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusParam   	30823569	       115 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlus2Params 	23545215	       155 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusAll     	 2134837	      1663 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseStatic  	44415607	        83.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseParam   	43003294	        81.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Parse2Params 	34613594	       105 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseAll     	 1238673	      2868 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_StaticAll    	   99607	     35951 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/julienschmidt/go-http-routing-benchmark	65.859s
```

**Local Benchmark**
```shell
goos: windows
goarch: amd64
pkg: github.com/julienschmidt/go-http-routing-benchmark
BenchmarkGin_Param              28237021               112 ns/op               0 B/op          0 allocs/op
BenchmarkGin_Param5             15618274               233 ns/op               0 B/op          0 allocs/op
BenchmarkGin_Param20             5198558               671 ns/op               0 B/op          0 allocs/op
BenchmarkGin_ParamWrite         17562182               204 ns/op               0 B/op          0 allocs/op
BenchmarkGin_GithubStatic       17266526               206 ns/op               0 B/op          0 allocs/op
BenchmarkGin_GithubParam         8999959               403 ns/op               0 B/op          0 allocs/op
BenchmarkGin_GithubAll             52173             69864 ns/op               0 B/op          0 allocs/op
BenchmarkGin_GPlusStatic        26471035               133 ns/op               0 B/op          0 allocs/op
BenchmarkGin_GPlusParam         18701162               192 ns/op               0 B/op          0 allocs/op
BenchmarkGin_GPlus2Params       13284082               262 ns/op               0 B/op          0 allocs/op
BenchmarkGin_GPlusAll            1357976              2629 ns/op               0 B/op          0 allocs/op
BenchmarkGin_ParseStatic        25174754               135 ns/op               0 B/op          0 allocs/op
BenchmarkGin_ParseParam         26181741               146 ns/op               0 B/op          0 allocs/op
BenchmarkGin_Parse2Params       20690522               173 ns/op               0 B/op          0 allocs/op
BenchmarkGin_ParseAll             757886              4629 ns/op               0 B/op          0 allocs/op
BenchmarkGin_StaticAll             59404             55964 ns/op               0 B/op          0 allocs/op
PASS
ok      github.com/julienschmidt/go-http-routing-benchmark      66.332s
```

**Comment by appleboy** [comment]
@qm012 Please provide the benchmark between **master** and PR and show the result of `benchstat` command.

**Comment by qm012** [comment]
The benchmarks:

**master** https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231184203
**this PR** https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231184328

The benchstat report:
**master**
```shell
BenchmarkGin_Param        	50492419	        72.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	29414568	       122 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	11018823	       320 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	28458553	       127 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	39511770	        91.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	22447558	       160 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubAll    	  112528	     31926 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusStatic  	55041181	        65.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusParam   	38489194	        93.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlus2Params 	30157081	       119 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusAll     	 2792388	      1289 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseStatic  	54590468	        66.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseParam   	47282571	        75.8 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Parse2Params 	41202753	        87.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseAll     	 1616793	      2225 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_StaticAll    	  150019	     24104 ns/op	       0 B/op	       0 allocs/op
```
**this PR**
```shell
BenchmarkGin_Param        	49536423	        73.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	24659034	       146 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 8172079	       432 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	27776470	       130 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	27761433	       130 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	15148544	       238 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubAll    	   83085	     48136 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusStatic  	38024416	        95.3 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusParam   	28010620	       137 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlus2Params 	23566668	       153 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GPlusAll     	 2082960	      1726 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseStatic  	42094258	        85.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseParam   	41519977	        86.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Parse2Params 	34881759	       103 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParseAll     	 1234374	      2920 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_StaticAll    	   99387	     36161 ns/op	       0 B/op	       0 allocs/op
```

**Comment by appleboy** [comment]
@qm012 I make the PR https://github.com/qm012/go-http-routing-benchmark/pull/1/files to change the go version and update the testing count. Please update the new result by `benchstat` tool below.

```sh
$ benchstat old.txt new.txt
name              old time/op    new time/op    delta
Gin_Param           72.0ns ± 0%    73.4ns ± 0%   ~     (p=1.000 n=1+1)
Gin_Param5           122ns ± 0%     146ns ± 0%   ~     (p=1.000 n=1+1)
Gin_Param20          320ns ± 0%     432ns ± 0%   ~     (p=1.000 n=1+1)
Gin_ParamWrite       127ns ± 0%     130ns ± 0%   ~     (p=1.000 n=1+1)
Gin_GithubStatic    91.2ns ± 0%   130.0ns ± 0%   ~     (p=1.000 n=1+1)
Gin_GithubParam      160ns ± 0%     238ns ± 0%   ~     (p=1.000 n=1+1)
Gin_GithubAll       31.9µs ± 0%    48.1µs ± 0%   ~     (p=1.000 n=1+1)
Gin_GPlusStatic     65.4ns ± 0%    95.3ns ± 0%   ~     (p=1.000 n=1+1)
Gin_GPlusParam      93.7ns ± 0%   137.0ns ± 0%   ~     (p=1.000 n=1+1)
Gin_GPlus2Params     119ns ± 0%     153ns ± 0%   ~     (p=1.000 n=1+1)
Gin_GPlusAll        1.29µs ± 0%    1.73µs ± 0%   ~     (p=1.000 n=1+1)
Gin_ParseStatic     66.0ns ± 0%    85.2ns ± 0%   ~     (p=1.000 n=1+1)
Gin_ParseParam      75.8ns ± 0%    86.4ns ± 0%   ~     (p=1.000 n=1+1)
Gin_Parse2Params    87.5ns ± 0%   103.0ns ± 0%   ~     (p=1.000 n=1+1)
Gin_ParseAll        2.23µs ± 0%    2.92µs ± 0%   ~     (p=1.000 n=1+1)
Gin_StaticAll       24.1µs ± 0%    36.2µs ± 0%   ~     (p=1.000 n=1+1)
```

**Comment by qm012** [comment]
hi, @appleboy Thanks you for reminding me.
The benchmarks:

**master** https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231194542
**this PR** https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231194421

The `benchstat` report:
```shell
$ benchstat old.txt new.txt
name              old time/op    new time/op    delta
Gin_Param           91.1ns ± 2%   119.2ns ± 4%  +30.92%  (p=0.000 n=10+10)
Gin_Param5           163ns ± 2%     253ns ± 3%  +54.70%  (p=0.000 n=9+10)
Gin_Param20          399ns ± 2%     712ns ± 8%  +78.57%  (p=0.000 n=9+10)
Gin_ParamWrite       174ns ± 1%     219ns ± 5%  +26.21%  (p=0.000 n=10+9)
Gin_GithubStatic     129ns ± 1%     223ns ± 1%  +72.08%  (p=0.000 n=9+9)
Gin_GithubParam      229ns ± 2%     429ns ± 2%  +87.68%  (p=0.000 n=10+9)
Gin_GithubAll       42.8µs ± 2%    73.0µs ± 2%  +70.56%  (p=0.000 n=9+10)
Gin_GPlusStatic     91.5ns ± 2%   147.0ns ± 2%  +60.60%  (p=0.000 n=10+9)
Gin_GPlusParam       137ns ± 2%     209ns ± 1%  +53.05%  (p=0.000 n=10+8)
Gin_GPlus2Params     180ns ± 1%     286ns ± 2%  +59.00%  (p=0.000 n=9+9)
Gin_GPlusAll        1.82µs ± 2%    2.86µs ± 1%  +57.30%  (p=0.000 n=10+10)
Gin_ParseStatic     99.3ns ± 3%   146.9ns ± 4%  +47.92%  (p=0.000 n=10+10)
Gin_ParseParam       106ns ± 1%     143ns ± 1%  +35.59%  (p=0.000 n=9+8)
Gin_Parse2Params     127ns ± 2%     183ns ± 3%  +43.87%  (p=0.000 n=10+10)
Gin_ParseAll        3.15µs ± 2%    4.90µs ± 2%  +55.56%  (p=0.000 n=10+10)
Gin_StaticAll       31.6µs ± 1%    59.4µs ± 2%  +87.94%  (p=0.000 n=9+10)

name              old alloc/op   new alloc/op   delta
Gin_Param            0.00B          0.00B          ~     (all equal)
Gin_Param5           0.00B          0.00B          ~     (all equal)
Gin_Param20          0.00B          0.00B          ~     (all equal)
Gin_ParamWrite       0.00B          0.00B          ~     (all equal)
Gin_GithubStatic     0.00B          0.00B          ~     (all equal)
Gin_GithubParam      0.00B          0.00B          ~     (all equal)
Gin_GithubAll        0.00B          0.00B          ~     (all equal)
Gin_GPlusStatic      0.00B          0.00B          ~     (all equal)
Gin_GPlusParam       0.00B          0.00B          ~     (all equal)
Gin_GPlus2Params     0.00B          0.00B          ~     (all equal)
Gin_GPlusAll         0.00B          0.00B          ~     (all equal)
Gin_ParseStatic      0.00B          0.00B          ~     (all equal)
Gin_ParseParam       0.00B          0.00B          ~     (all equal)
Gin_Parse2Params     0.00B          0.00B          ~     (all equal)
Gin_ParseAll         0.00B          0.00B          ~     (all equal)
Gin_StaticAll        0.00B          0.00B          ~     (all equal)

name              old allocs/op  new allocs/op  delta
Gin_Param             0.00           0.00          ~     (all equal)
Gin_Param5            0.00           0.00          ~     (all equal)
Gin_Param20           0.00           0.00          ~     (all equal)
Gin_ParamWrite        0.00           0.00          ~     (all equal)
Gin_GithubStatic      0.00           0.00          ~     (all equal)
Gin_GithubParam       0.00           0.00          ~     (all equal)
Gin_GithubAll         0.00           0.00          ~     (all equal)
Gin_GPlusStatic       0.00           0.00          ~     (all equal)
Gin_GPlusParam        0.00           0.00          ~     (all equal)
Gin_GPlus2Params      0.00           0.00          ~     (all equal)
Gin_GPlusAll          0.00           0.00          ~     (all equal)
Gin_ParseStatic       0.00           0.00          ~     (all equal)
Gin_ParseParam        0.00           0.00          ~     (all equal)
Gin_Parse2Params      0.00           0.00          ~     (all equal)
Gin_ParseAll          0.00           0.00          ~     (all equal)
Gin_StaticAll         0.00           0.00          ~     (all equal)
```

**Comment by qm012** [comment]
Benchstat report of the newly submitted Code:
```shell
$ benchstat old.txt new.txt
name              old time/op    new time/op    delta
Gin_Param           93.5ns ± 5%    99.5ns ± 0%   +6.49%  (p=0.000 n=10+7)
Gin_Param5           166ns ± 2%     216ns ± 1%  +30.03%  (p=0.000 n=10+9)
Gin_Param20          407ns ± 2%     612ns ± 1%  +50.42%  (p=0.000 n=10+9)
Gin_ParamWrite       177ns ± 2%     187ns ± 2%   +5.51%  (p=0.000 n=9+9)
Gin_GithubStatic     135ns ± 1%     193ns ± 2%  +43.04%  (p=0.000 n=9+10)
Gin_GithubParam      236ns ± 5%     367ns ± 1%  +55.40%  (p=0.000 n=10+9)
Gin_GithubAll       43.8µs ± 2%    62.1µs ± 3%  +41.81%  (p=0.000 n=10+9)
Gin_GPlusStatic     93.9ns ± 3%   123.6ns ± 2%  +31.58%  (p=0.000 n=9+9)
Gin_GPlusParam       139ns ± 1%     184ns ± 2%  +31.82%  (p=0.000 n=9+9)
Gin_GPlus2Params     183ns ± 1%     246ns ± 2%  +34.41%  (p=0.000 n=10+8)
Gin_GPlusAll        1.84µs ± 2%    2.49µs ± 2%  +35.36%  (p=0.000 n=10+9)
Gin_ParseStatic     93.2ns ± 1%   131.3ns ± 1%  +40.90%  (p=0.000 n=10+9)
Gin_ParseParam       108ns ± 2%     129ns ± 1%  +20.13%  (p=0.000 n=10+8)
Gin_Parse2Params     133ns ± 3%     160ns ± 1%  +20.37%  (p=0.000 n=9+9)
Gin_ParseAll        3.11µs ± 1%    4.32µs ± 2%  +38.70%  (p=0.000 n=8+10)
Gin_StaticAll       32.3µs ± 2%    51.2µs ± 1%  +58.16%  (p=0.000 n=10+10)
```
I will continue to optimize the report, but the current result is not very ideal
Root: Search the route tree for secondary route matching rules
```go
// match '/', If this condition is matched, the next route is found
if strings.HasSuffix(n.path, "/") || strings.Contains(n.fullPath, ":") || n.path == "" {
	matchNum++
}
```
Thank you all for your reviews.😆

**Comment by qm012** [comment]
The benchmarks:
**master** https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231194542
**this PR** https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231313687

The `benchstat` report:
```shell
name              old time/op    new time/op    delta
Gin_Param           62.5ns ± 4%    64.0ns ± 5%     ~     (p=0.110 n=10+10)
Gin_Param5           110ns ± 3%     114ns ± 5%   +3.31%  (p=0.017 n=10+10)
Gin_Param20          276ns ± 2%     298ns ± 3%   +7.92%  (p=0.000 n=10+10)
Gin_ParamWrite       118ns ± 2%     120ns ± 5%     ~     (p=0.136 n=10+10)
Gin_GithubStatic    78.3ns ± 2%    96.4ns ± 2%  +23.07%  (p=0.000 n=10+10)
Gin_GithubParam      129ns ± 0%     177ns ± 2%  +37.55%  (p=0.000 n=10+10)
Gin_GithubAll       25.5µs ± 0%    32.1µs ± 1%  +26.01%  (p=0.000 n=10+10)
Gin_GPlusStatic     62.7ns ± 0%    69.5ns ± 2%  +10.90%  (p=0.000 n=10+10)
Gin_GPlusParam      88.6ns ± 3%   105.4ns ± 2%  +18.98%  (p=0.000 n=10+10)
Gin_GPlus2Params     112ns ± 2%     138ns ± 1%  +23.81%  (p=0.000 n=10+10)
Gin_GPlusAll        1.14µs ± 1%    1.38µs ± 1%  +20.95%  (p=0.000 n=10+9)
Gin_ParseStatic     59.2ns ± 0%    67.1ns ± 2%  +13.25%  (p=0.000 n=10+10)
Gin_ParseParam      70.6ns ± 4%    75.7ns ± 2%   +7.22%  (p=0.000 n=10+10)
Gin_Parse2Params    83.3ns ± 1%    90.8ns ± 1%   +8.95%  (p=0.000 n=9+10)
Gin_ParseAll        1.97µs ± 1%    2.27µs ± 1%  +15.50%  (p=0.000 n=10+10)
Gin_StaticAll       18.6µs ± 0%    25.0µs ± 1%  +34.31%  (p=0.000 n=10+10)
```

**Comment by qm012** [comment]
hi @appleboy I updated the code, and when looking for the contents of the test report, I found that the relevant code submitted with (#2706) maintained two nodes, which would cause the test report to fail to get the expected results, so I made changes and optimizations. By maintaining a node, I controlled the way to find nodes, and made several cross-test reports for comparison when judging test conditions, and got an acceptable final result. Thank you for your help and review.

The benchmarks:

branch| benchmark| running time
:-: | :-: | :-: 
**`master`**  | https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231451724 | 634.111s
**`this PR`**  | https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231449191 | 633.627s 

The benchstat report:
```shell
name              old time/op    new time/op    delta
Gin_Param           63.5ns ± 4%    62.6ns ± 4%    ~     (p=0.448 n=10+10)
Gin_Param5           112ns ± 6%     114ns ± 3%    ~     (p=0.109 n=10+10)
Gin_Param20          282ns ± 3%     297ns ± 1%  +5.47%  (p=0.000 n=10+10)
Gin_ParamWrite       119ns ± 5%     118ns ± 2%    ~     (p=0.566 n=10+10)
Gin_GithubStatic    81.2ns ± 6%    79.3ns ± 0%    ~     (p=0.085 n=10+10)
Gin_GithubParam      128ns ± 6%     132ns ± 1%  +2.64%  (p=0.006 n=10+10)
Gin_GithubAll       26.2µs ± 3%    27.1µs ± 1%  +3.10%  (p=0.004 n=10+10)
Gin_GPlusStatic     66.0ns ± 3%    63.3ns ± 2%  -4.17%  (p=0.000 n=10+10)
Gin_GPlusParam      91.2ns ± 3%    86.1ns ± 1%  -5.62%  (p=0.000 n=10+10)
Gin_GPlus2Params     117ns ± 5%     110ns ± 1%  -6.32%  (p=0.000 n=9+10)
Gin_GPlusAll        1.23µs ± 7%    1.22µs ± 0%    ~     (p=1.000 n=10+8)
Gin_ParseStatic     62.4ns ± 5%    61.9ns ± 1%    ~     (p=0.218 n=10+10)
Gin_ParseParam      70.2ns ± 6%    68.3ns ± 1%    ~     (p=0.184 n=10+10)
Gin_Parse2Params    82.5ns ± 4%    83.7ns ± 1%  +1.49%  (p=0.014 n=10+9)
Gin_ParseAll        2.01µs ± 3%    2.05µs ± 2%    ~     (p=0.287 n=10+10)
Gin_StaticAll       18.9µs ± 3%    19.4µs ± 1%  +2.93%  (p=0.000 n=10+10)
```

**Comment by appleboy** [comment]
@g1eny0ung Please also take look at it. https://github.com/gin-gonic/gin/pull/2767#issuecomment-871934041

**Comment by g1eny0ung** [comment]
> @g1eny0ung Please also take look at it. [#2767 (comment)](https://github.com/gin-gonic/gin/pull/2767#issuecomment-871934041)

I'll take a look these few days. Sorry because I'm a little busy this week. 😵

**Comment by qm012** [comment]
hi @appleboy After a lot of cross-testing and comparison, the latest feedback test report is very exciting.I also tried to match '/' in another way, but the final result was not satisfactory.
[source code](https://github.com/qm012/gin/compare/vtest16...test) 
[benchmark](https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231584656)

The latest benchmarks:
branch| benchmark| running time
:-: | :-: | :-: 
**`master`**  | https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231451724 | 634.111s
**`this PR`**  | https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231589953 | 631.022s

The latest benchstat report:
```shell
name              old time/op    new time/op    delta
Gin_Param           63.5ns ± 4%    60.6ns ± 1%   -4.54%  (p=0.000 n=10+10)
Gin_Param5           112ns ± 6%     103ns ± 1%   -7.63%  (p=0.000 n=10+9)
Gin_Param20          282ns ± 3%     259ns ± 3%   -7.91%  (p=0.000 n=10+10)
Gin_ParamWrite       119ns ± 5%     117ns ± 3%     ~     (p=0.160 n=10+10)
Gin_GithubStatic    81.2ns ± 6%    71.9ns ± 2%  -11.36%  (p=0.000 n=10+10)
Gin_GithubParam      128ns ± 6%     119ns ± 1%   -7.16%  (p=0.000 n=10+10)
Gin_GithubAll       26.2µs ± 3%    25.3µs ± 1%   -3.41%  (p=0.000 n=10+10)
Gin_GPlusStatic     66.0ns ± 3%    58.2ns ± 2%  -11.86%  (p=0.000 n=10+10)
Gin_GPlusParam      91.2ns ± 3%    76.0ns ± 2%  -16.70%  (p=0.000 n=10+8)
Gin_GPlus2Params     117ns ± 5%      95ns ± 1%  -19.17%  (p=0.000 n=9+8)
Gin_GPlusAll        1.23µs ± 7%    1.09µs ± 2%  -11.36%  (p=0.000 n=10+10)
Gin_ParseStatic     62.4ns ± 5%    62.0ns ± 2%     ~     (p=0.280 n=10+10)
Gin_ParseParam      70.2ns ± 6%    69.0ns ± 4%     ~     (p=0.218 n=10+10)
Gin_Parse2Params    82.5ns ± 4%    83.0ns ± 2%     ~     (p=0.271 n=10+10)
Gin_ParseAll        2.01µs ± 3%    1.94µs ± 2%   -3.86%  (p=0.008 n=10+10)
Gin_StaticAll       18.9µs ± 3%    18.4µs ± 1%   -2.59%  (p=0.005 n=10+10)
```

File: tree_test.go [hunk 3]
```diff
@@ -154,6 +154,12 @@ func TestTreeWildcard(t *testing.T) {
 		"/info/:user/public",
 		"/info/:user/project/:project",
 		"/info/:user/project/golang",
+		"/aa/*xx",
+		"/ab/*xx",
+		"/:cc",
+		"/:cc/cc",
+		"/get/test/abc/",
+		"/get/:param/abc/",
```
Comment (rw-access) [inline tree_test.go:162]: can you add more routes with multiple params?
I also want to confirm something like this:
```
/something/:paramname/thirdthing
/something/secondthing/test
```

If you someone does `GET /something/secondthing/thirdthing` that should have a 404

File: tree.go [hunk 4]
```diff
@@ -418,32 +429,41 @@ walk: // Outer loop for walking the tree
...
+					n = latestNode
+				}
+
 				// If there is no wildcard pattern, recommend a redirection
 				if !n.wildChild {
 					// Nothing found.
 					// We can recommend to redirect to the same URL without a
 					// trailing slash if a leaf exists for that path.
-					value.tsr = (path == "/" && n.handlers != nil)
+					value.tsr = path == "/" && n.handlers != nil
```
Comment (rw-access) [inline tree.go:466]: my personal preference is to keep the parentheses, as they make it more clear you're assigning a boolean expression
```suggestion
					value.tsr = (path == "/" && n.handlers != nil)
```

File: .gitignore [hunk 5]
```diff
@@ -4,4 +4,4 @@ coverage.out
 count.out
 test
 profile.out
-tmp.out
+tmp.out
```
Comment (rw-access) [inline .gitignore:7]: restore newline
```suggestion
tmp.out

```

Comment (qm012) [reply .gitignore]: done,thanks.

File: tree.go (hunk 4 above)
Comment (qm012) [reply tree.go:466]: Thank you for your review, I see what you mean, but for a obsessive-compulsive disorder patients, in fact the parentheses is invalid and can be ignored, just had prompt effect (but not enough concise), if the judge conditions for more than two or more, or is too long, can adopt the way of line, I'm sorry, I want to insist on my opinion.

File: tree_test.go (hunk 3 above)
Comment (qm012) [reply tree_test.go:162]: Thank you for your review. I need some time to do the test. The final result should be 404 is correct

Comment (qm012) [reply tree_test.go:166]: hi @rw-access 
1. Added more unit tests
2. This scene I tested ` GET/something/secondthing thirdthing ` matching ` / something / : paramname/thirdthing ` is correct
    When n.indices matches a child node, 'line 271 n.hildren [len(n.hildren)-1]' will be executed if it does not
```
`GET /something/secondthing/abc` 404
`GET /something/secondthing/ff` 404
```
n

File: tree.go (hunk 4 above)
Comment (qm012) [reply tree.go:466]: #### There will also be differences in style
https://github.com/gin-gonic/gin/blob/9c27053243cb24ecc90d01c8ff379bd98fed9c8e/tree.go#L502

#### It makes sense under conditions like this

```go
var condition = (a &b) || 
                       (c && d)
```
https://github.com/gin-gonic/gin/blob/9c27053243cb24ecc90d01c8ff379bd98fed9c8e/tree.go#L558

**Comment by appleboy** [comment]
maybe we can bump the new version v1.7.3 after merge this PR.

cc @thinkerou

**Comment by thinkerou** [comment]
> maybe we can bump the new version v1.7.3 after merge this PR.
> 
> cc @thinkerou

Yes 👍

**Comment by thinkerou** [comment]
> hi @appleboy After a lot of cross-testing and comparison, the latest feedback test report is very exciting.I also tried to match '/' in another way, but the final result was not satisfactory.
> [source code](https://github.com/qm012/gin/compare/vtest16...test)
> [benchmark](https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231584656)
> 
> The latest benchmarks:
> 
> branch	benchmark	running time
> **`master`**	https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231451724	634.111s
> **`this PR`**	https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231589953	631.022s
> The latest benchstat report:
> 
> ```shell
> name              old time/op    new time/op    delta
> Gin_Param           63.5ns ± 4%    60.6ns ± 1%   -4.54%  (p=0.000 n=10+10)
> Gin_Param5           112ns ± 6%     103ns ± 1%   -7.63%  (p=0.000 n=10+9)
> Gin_Param20          282ns ± 3%     259ns ± 3%   -7.91%  (p=0.000 n=10+10)
> Gin_ParamWrite       119ns ± 5%     117ns ± 3%     ~     (p=0.160 n=10+10)
> Gin_GithubStatic    81.2ns ± 6%    71.9ns ± 2%  -11.36%  (p=0.000 n=10+10)
> Gin_GithubParam      128ns ± 6%     119ns ± 1%   -7.16%  (p=0.000 n=10+10)
> Gin_GithubAll       26.2µs ± 3%    25.3µs ± 1%   -3.41%  (p=0.000 n=10+10)
> Gin_GPlusStatic     66.0ns ± 3%    58.2ns ± 2%  -11.86%  (p=0.000 n=10+10)
> Gin_GPlusParam      91.2ns ± 3%    76.0ns ± 2%  -16.70%  (p=0.000 n=10+8)
> Gin_GPlus2Params     117ns ± 5%      95ns ± 1%  -19.17%  (p=0.000 n=9+8)
> Gin_GPlusAll        1.23µs ± 7%    1.09µs ± 2%  -11.36%  (p=0.000 n=10+10)
> Gin_ParseStatic     62.4ns ± 5%    62.0ns ± 2%     ~     (p=0.280 n=10+10)
> Gin_ParseParam      70.2ns ± 6%    69.0ns ± 4%     ~     (p=0.218 n=10+10)
> Gin_Parse2Params    82.5ns ± 4%    83.0ns ± 2%     ~     (p=0.271 n=10+10)
> Gin_ParseAll        2.01µs ± 3%    1.94µs ± 2%   -3.86%  (p=0.008 n=10+10)
> Gin_StaticAll       18.9µs ± 3%    18.4µs ± 1%   -2.59%  (p=0.005 n=10+10)
> ```

@qm012 thanks a lot!
can you run benchmark test using the latest pr code again? thanks!

**Comment by qm012** [comment]
@thinkerou @applePlease wait for me to test the test report of a conditional judgment. I will reply to you laterboy ,thanks

**Comment by qm012** [comment]
> > hi @appleboy After a lot of cross-testing and comparison, the latest feedback test report is very exciting.I also tried to match '/' in another way, but the final result was not satisfactory.
> > [source code](https://github.com/qm012/gin/compare/vtest16...test)
> > [benchmark](https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231584656)
> > The latest benchmarks:
> > branch	benchmark	running time
> > **`master`**	https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231451724	634.111s
> > **`this PR`**	https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231589953	631.022s
> > The latest benchstat report:
> > ```shell
> > name              old time/op    new time/op    delta
> > Gin_Param           63.5ns ± 4%    60.6ns ± 1%   -4.54%  (p=0.000 n=10+10)
> > Gin_Param5           112ns ± 6%     103ns ± 1%   -7.63%  (p=0.000 n=10+9)
> > Gin_Param20          282ns ± 3%     259ns ± 3%   -7.91%  (p=0.000 n=10+10)
> > Gin_ParamWrite       119ns ± 5%     117ns ± 3%     ~     (p=0.160 n=10+10)
> > Gin_GithubStatic    81.2ns ± 6%    71.9ns ± 2%  -11.36%  (p=0.000 n=10+10)
> > Gin_GithubParam      128ns ± 6%     119ns ± 1%   -7.16%  (p=0.000 n=10+10)
> > Gin_GithubAll       26.2µs ± 3%    25.3µs ± 1%   -3.41%  (p=0.000 n=10+10)
> > Gin_GPlusStatic     66.0ns ± 3%    58.2ns ± 2%  -11.86%  (p=0.000 n=10+10)
> > Gin_GPlusParam      91.2ns ± 3%    76.0ns ± 2%  -16.70%  (p=0.000 n=10+8)
> > Gin_GPlus2Params     117ns ± 5%      95ns ± 1%  -19.17%  (p=0.000 n=9+8)
> > Gin_GPlusAll        1.23µs ± 7%    1.09µs ± 2%  -11.36%  (p=0.000 n=10+10)
> > Gin_ParseStatic     62.4ns ± 5%    62.0ns ± 2%     ~     (p=0.280 n=10+10)
> > Gin_ParseParam      70.2ns ± 6%    69.0ns ± 4%     ~     (p=0.218 n=10+10)
> > Gin_Parse2Params    82.5ns ± 4%    83.0ns ± 2%     ~     (p=0.271 n=10+10)
> > Gin_ParseAll        2.01µs ± 3%    1.94µs ± 2%   -3.86%  (p=0.008 n=10+10)
> > Gin_StaticAll       18.9µs ± 3%    18.4µs ± 1%   -2.59%  (p=0.005 n=10+10)
> > ```
> 
> @qm012 thanks a lot!
> can you run benchmark test using the latest pr code again? thanks!

1. The previous test report was better because I removed the 'value.tsr' match, but that would have caused a TSR error, and I have restored that piece of code
https://github.com/gin-gonic/gin/blob/9c27053243cb24ecc90d01c8ff379bd98fed9c8e/tree.go#L576

2. There will be a derived bug matching to 'Level 1 Router' parameter in the current bug, and one bit will be intercepted. I wanted to open a new PR to fix it before, but I didn't put it in this PR. Can I deal with it like this?

The latest benchmarks:

branch| benchmark| running time
:-: | :-: | :-: 
**`master`**  | https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231451724 | 634.111s
**`this PR`** | https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231780043 | 634.919s

The latest  benchstat report:
```shell
name              old time/op    new time/op    delta
Gin_Param           63.5ns ± 4%    60.4ns ± 1%   -4.87%  (p=0.000 n=10+9)
Gin_Param5           112ns ± 6%     119ns ± 4%   +6.74%  (p=0.000 n=10+10)
Gin_Param20          282ns ± 3%     310ns ± 2%  +10.09%  (p=0.000 n=10+10)
Gin_ParamWrite       119ns ± 5%     115ns ± 1%   -3.23%  (p=0.003 n=10+10)
Gin_GithubStatic    81.2ns ± 6%    80.6ns ± 2%     ~     (p=0.579 n=10+10)
Gin_GithubParam      128ns ± 6%     138ns ± 2%   +7.66%  (p=0.000 n=10+10)
Gin_GithubAll       26.2µs ± 3%    27.8µs ± 0%   +5.99%  (p=0.000 n=10+10)
Gin_GPlusStatic     66.0ns ± 3%    61.6ns ± 2%   -6.70%  (p=0.000 n=10+10)
Gin_GPlusParam      91.2ns ± 3%    91.7ns ± 0%     ~     (p=0.500 n=10+8)
Gin_GPlus2Params     117ns ± 5%     119ns ± 0%   +1.30%  (p=0.003 n=9+10)
Gin_GPlusAll        1.23µs ± 7%    1.20µs ± 1%     ~     (p=0.671 n=10+10)
Gin_ParseStatic     62.4ns ± 5%    60.1ns ± 1%   -3.60%  (p=0.001 n=10+10)
Gin_ParseParam      70.2ns ± 6%    66.8ns ± 1%   -4.83%  (p=0.000 n=10+9)
Gin_Parse2Params    82.5ns ± 4%    84.3ns ± 0%   +2.29%  (p=0.001 n=10+10)
Gin_ParseAll        2.01µs ± 3%    1.99µs ± 1%     ~     (p=0.469 n=10+10)
Gin_StaticAll       18.9µs ± 3%    19.7µs ± 0%   +4.49%  (p=0.000 n=10+10)
```

File: tree.go [hunk 6]
```diff
@@ -535,6 +567,10 @@ walk: // Outer loop for walking the tree
 		}
 
 		if path == prefix {
+			// level 2 router not found and latestNode.wildChild is ture
```
Comment (rw-access) [inline tree.go:570]:
```suggestion
			// level 2 router not found and latestNode.wildChild is true
```

Comment (qm012) [reply tree.go]: done,thanks.😵

**Comment by appleboy** [comment]
```go
Gin_Param5           112ns ± 6%     119ns ± 4%   +6.74%  (p=0.000 n=10+10)
Gin_Param20          282ns ± 3%     310ns ± 2%  +10.09%  (p=0.000 n=10+10)
```

@rw-access @g1eny0ung any suggestion about this?

**Comment by qm012** [comment]
hi @appleboy @rw-access @thinkerou  I updated the code

The latest benchmarks:

branch| benchmark| running time
:-: | :-: | :-: 
**`master`**  | https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231451724 | 634.111s
**`this PR`** | https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231897300 | 634.952s

The latest  benchstat report:
```shell
name              old time/op    new time/op    delta
Gin_Param           63.5ns ± 4%    61.3ns ± 1%  -3.52%  (p=0.001 n=10+10)
Gin_Param5           112ns ± 6%     116ns ± 1%  +4.02%  (p=0.002 n=10+9)
Gin_Param20          282ns ± 3%     305ns ± 1%  +8.33%  (p=0.000 n=10+9)
Gin_ParamWrite       119ns ± 5%     116ns ± 2%  -2.97%  (p=0.015 n=10+10)
Gin_GithubStatic    81.2ns ± 6%    80.3ns ± 0%    ~     (p=0.172 n=10+10)
Gin_GithubParam      128ns ± 6%     136ns ± 1%  +6.49%  (p=0.000 n=10+10)
Gin_GithubAll       26.2µs ± 3%    28.1µs ± 0%  +7.26%  (p=0.000 n=10+10)
Gin_GPlusStatic     66.0ns ± 3%    61.4ns ± 0%  -6.93%  (p=0.000 n=10+10)
Gin_GPlusParam      91.2ns ± 3%    83.3ns ± 0%  -8.65%  (p=0.000 n=10+10)
Gin_GPlus2Params     117ns ± 5%     108ns ± 0%  -8.00%  (p=0.000 n=9+9)
Gin_GPlusAll        1.23µs ± 7%    1.19µs ± 0%    ~     (p=0.464 n=10+10)
Gin_ParseStatic     62.4ns ± 5%    60.7ns ± 1%  -2.75%  (p=0.002 n=10+10)
Gin_ParseParam      70.2ns ± 6%    68.0ns ± 0%  -3.08%  (p=0.002 n=10+9)
Gin_Parse2Params    82.5ns ± 4%    85.8ns ± 0%  +4.11%  (p=0.000 n=10+9)
Gin_ParseAll        2.01µs ± 3%    1.99µs ± 0%    ~     (p=0.466 n=10+10)
```

**Comment by qm012** [comment]
hi erveryone,more balanced test reporting

The latest benchmarks:

branch| benchmark| running time
:-: | :-: | :-: 
**`master`**  | https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/231451724 | 634.111s
**`this PR`** | https://travis-ci.com/github/qm012/go-http-routing-benchmark/builds/232107973 | 633.919s

The latest benchstat report:
```shell
name              old time/op    new time/op    delta
Gin_Param           63.5ns ± 4%    61.4ns ± 5%  -3.31%  (p=0.019 n=10+10)
Gin_Param5           112ns ± 6%     115ns ± 3%  +2.95%  (p=0.012 n=10+10)
Gin_Param20          282ns ± 3%     304ns ± 2%  +7.79%  (p=0.000 n=10+10)
Gin_ParamWrite       119ns ± 5%     117ns ± 3%    ~     (p=0.102 n=10+10)
Gin_GithubStatic    81.2ns ± 6%    78.4ns ± 2%  -3.44%  (p=0.009 n=10+10)
Gin_GithubParam      128ns ± 6%     133ns ± 1%  +3.73%  (p=0.001 n=10+10)
Gin_GithubAll       26.2µs ± 3%    27.1µs ± 0%  +3.31%  (p=0.004 n=10+10)
Gin_GPlusStatic     66.0ns ± 3%    62.7ns ± 2%  -5.00%  (p=0.000 n=10+10)
Gin_GPlusParam      91.2ns ± 3%    91.4ns ± 2%    ~     (p=0.796 n=10+10)
Gin_GPlus2Params     117ns ± 5%     117ns ± 1%    ~     (p=1.000 n=9+10)
Gin_GPlusAll        1.23µs ± 7%    1.19µs ± 1%    ~     (p=0.565 n=10+10)
Gin_ParseStatic     62.4ns ± 5%    59.9ns ± 1%  -3.92%  (p=0.001 n=10+10)
Gin_ParseParam      70.2ns ± 6%    68.1ns ± 1%  -2.88%  (p=0.023 n=10+10)
Gin_Parse2Params    82.5ns ± 4%    83.8ns ± 1%    ~     (p=0.089 n=10+10)
Gin_ParseAll        2.01µs ± 3%    1.96µs ± 1%  -2.91%  (p=0.003 n=10+10)
Gin_StaticAll       18.9µs ± 3%    19.1µs ± 0%    ~     (p=0.156 n=10+9)
```

**Comment by appleboy** [comment]
LGTM, need @g1eny0ung @thinkerou @rw-access review and confirm.

**Review by thinkerou — APPROVED** [review]
lgtm

**Review by appleboy — APPROVED** [review]

**Comment by thinkerou** [comment]
> maybe we can bump the new version v1.7.3 after merge this PR.
> 
> cc @thinkerou

merge and bump v1.7.3? thanks!

**Comment by appleboy** [comment]
@thinkerou we can't release the v1.7.3 version since of the issue https://github.com/gin-gonic/gin/issues/2786

@qm012 I can reproduce the issue with the latest commit https://github.com/gin-gonic/gin/commit/d4ca9a0fb1211108f0a893634ee01b0006890c16

```go
package main

import (
	"fmt"

	"github.com/gin-gonic/gin"
)

func handler01(c *gin.Context) {
	fmt.Println(c.Params)
	c.String(200, "ok01")
}

func handler02(c *gin.Context) {
	fmt.Println(c.Params)
	c.String(200, "ok02")
}

func main() {
	g := gin.Default()
	g.GET("/get/abc", handler01)
	g.GET("/get/:param", handler02)
	g.Run(":9090")
}
```

result:

```sh
/abc  200 ok02
/a    404
/ab   200 ok02
/xyz  200 ok02
/abcd 200 ok02
```

**Comment by sdojjy** [comment]
```
package main

import "github.com/gin-gonic/gin"

func main() {
	r := gin.Default()

	r.GET("/aa/:customer", newHandler("/aa/:customer"))
	r.GET("/aa/:customer/files/:file", newHandler("/aa/:customer/files/:file"))

	r.Run() // listen and serve on 0.0.0.0:8080
}

func newHandler(t string) func(c *gin.Context) {
	return func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": t,
		})
	}
}
```

@qm012 @appleboy 
For the above code example, the request results are:
```
/aa/1/files/aa  => /aa/:customer/files/:file
/aa/1/files/    =>  /aa/:customer
/aa/1/files    =>  404
/aa/1           =>  /aa/:customer
```
Is it by design?

**Comment by qm012** [comment]
@sdojjy No, the test cases have not been fully covered. Thank you for your feedback.

**Comment by averageflow** [comment]
this brought problems thus I am now frozen at #2878
