### PR TITLE
fix(context): check handler is nil

### LINKED ISSUE #3404: what happened? /github.com/gin-gonic/gin/context.go:173 (0x47f51d3)   (*Context).Next: c.handlers[c.index](c)
what happened
```
	github.com/gin-contrib/expvar v0.0.1
	github.com/gin-contrib/gzip v0.0.5
	github.com/gin-contrib/pprof v1.4.0
	github.com/gin-contrib/sessions v0.0.5
	github.com/gin-contrib/static v0.0.1
	github.com/gin-gonic/gin v1.8.1
	github.com/gin-contrib/sse v0.1.0 // indirect
	github.com/onsi/ginkgo v1.16.5 // indirect
	google.golang.org/appengine v1.6.7 // indirect
```

code
```
router.Use(func(c *gin.Context) {
		start := time.Now()
		if nil != c {
			c.Next()
		}
		end := time.Now()
		latency := end.Sub(start)

		fmt.Printf("%15s %3d %4s %15s %s\n", latency, c.Writer.Status(), c.Request.Method, c.ClientIP(), c.Request.URL.Path)
	})
```

```
2022/11/18 17:51:08 [Recovery] 2022/11/18 - 17:51:08 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/Cellar/go@1.18/1.18.6/libexec/src/runtime/panic.go:220 (0x403ac24)
        panicmem: panic(memoryError)
/usr/local/Cellar/go@1.18/1.18.6/libexec/src/runtime/signal_unix.go:818 (0x405353c)
        sigpanic: panicmem()
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-gonic/gin/context.go:173 (0x47f51d3)
        (*Context).Next: c.handlers[c.index](c)
/Users/51pwn/MyWork/goSqlite_gorm/pkg/server/sec.go:27 (0x5cebc67)
        InitSecRouter.func1: c.Next()
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-gonic/gin/context.go:173 (0x47f51dc)
        (*Context).Next: c.handlers[c.index](c)
/Users/51pwn/MyWork/goSqlite_gorm/pkg/brotlimd/handler.go:221 (0x5bd20ab)
        (*Handler).Gin: ctx.Next()
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-gonic/gin/context.go:173 (0x47f51dc)
        (*Context).Next: c.handlers[c.index](c)
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-contrib/gzip/handler.go:60 (0x5b63304)
        (*gzipHandler).Handle: c.Next()
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-gonic/gin/context.go:173 (0x47f51dc)
        (*Context).Next: c.handlers[c.index](c)
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-contrib/sessions/sessions.go:54 (0x5b6dd37)
        Sessions.func1: c.Next()
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-gonic/gin/context.go:173 (0x47f51dc)
        (*Context).Next: c.handlers[c.index](c)
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-gonic/gin/logger.go:240 (0x4806e31)
        LoggerWithConfig.func1: c.Next()
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-gonic/gin/context.go:173 (0x47f51dc)
        (*Context).Next: c.handlers[c.index](c)
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-gonic/gin/recovery.go:101 (0x4808477)
        CustomRecoveryWithWriter.func1: c.Next()
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-gonic/gin/context.go:173 (0x47f51dc)
        (*Context).Next: c.handlers[c.index](c)
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-gonic/gin/gin.go:616 (0x4804a28)
        (*Engine).handleHTTPRequest: c.Next()
/Users/51pwn/MyWork/goSqlite_gorm/vendor/github.com/gin-gonic/gin/gin.go:572 (0x48044fa)
        (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/Users/51pwn/MyWork/goSqlite_gorm/vendor/golang.org/x/net/http2/h2c/h2c.go:125 (0x47e3b5b)
        h2cHandler.ServeHTTP: s.Handler.ServeHTTP(w, r)
/usr/local/Cellar/go@1.18/1.18.6/libexec/src/net/http/server.go:2916 (0x44ac813)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/Cellar/go@1.18/1.18.6/libexec/src/net/http/server.go:3523 (0x44af6f2)
        initALPNRequest.ServeHTTP: h.h.ServeHTTP(rw, req)
/usr/local/Cellar/go@1.18/1.18.6/libexec/src/net/http/h2_bundle.go:5907 (0x4467a27)
        (*http2serverConn).runHandler: handler(rw, req)
/usr/local/Cellar/go@1.18/1.18.6/libexec/src/runtime/asm_amd64.s:1571 (0x4071660)
        goexit: BYTE    $0x90   // NOP

```

### PR DESCRIPTION
**Pull request by hktalent**
fix #3404

### CODE REVIEW

File: context.go [hunk 1]
```diff
@@ -141,7 +141,9 @@ func (c *Context) HandlerName() string {
 func (c *Context) HandlerNames() []string {
 	hn := make([]string, 0, len(c.handlers))
 	for _, val := range c.handlers {
-		hn = append(hn, nameOfFunction(val))
+		if nil != val {
```
Comment (appleboy) [inline context.go:144]: if val != nil

File: context.go [hunk 2]
```diff
@@ -171,7 +173,9 @@ func (c *Context) FullPath() string {
 func (c *Context) Next() {
 	c.index++
 	for c.index < int8(len(c.handlers)) {
-		c.handlers[c.index](c)
+		if nil != c.handlers[c.index] {
```
Comment (appleboy) [inline context.go:176]: if xxx != nil

**Review by appleboy — CHANGES_REQUESTED** [review]

**Comment by appleboy** [comment]
Please also add some testing.

**Comment by appleboy** [comment]
@hktalent Any updates?

**Review by appleboy — DISMISSED** [review]

**Review by appleboy — APPROVED** [review]
