### PR TITLE
fix(uri): query binding bug

### LINKED ISSUE #3235: Wrong query binding struct tag
https://github.com/gin-gonic/gin/blob/b57163a0e4339d7feb393ff430a454f4e448cf9c/binding/query.go#L15-L21

`mapForm` searches `form` struct tag, not `query`

Fixed version:

```go
func (q queryBinding) Bind(req *http.Request, obj any) error {
	values := req.URL.Query()
	if err := mapFormByTag(obj, values, q.Name() ); err != nil {
		return err
	}
	return validate(obj)
}
```

### PR DESCRIPTION
**Pull request by illiafox**
#3235 Reference

Changes: 
- [#e837e1c](https://github.com/gin-gonic/gin/commit/e837e1cd1850559d91d921b712bc7b0c8f78cf7e) changed query mapping function
- [#c17e9f1](https://github.com/gin-gonic/gin/commit/c17e9f1a1554d4a32d44131cf6f949606814ffbe) tests

### CODE REVIEW

**Review by Snawoot — APPROVED** [review]

**Review by Boborikin — APPROVED** [review]

File: binding/query_test.go [hunk 1]
```diff
@@ -0,0 +1,23 @@
+package binding
```
Comment (thinkerou) [inline binding/query_test.go:1]: please add copyright, thanks!

**Comment by illiafox** [comment]
The original pull requests was from master branch, but I have committed changes to the [fix/query-bind](https://github.com/illiafox/gin/tree/fix/query-bind) branch. Shall I create another pull request or merge into master?

**Comment by appleboy** [comment]
@illiafox you can change the pull request branch by yourself.

image
