### PR TITLE
binding: add support of multipart multi files (#1878)

### LINKED ISSUE #1878: how to binding for multi files upload
#1263's merged solution take no effect for multi files uploading.

my code:
```go
// MailUpload struct for e-mail
type MailUpload struct {
	Mail string 			     `json:"mail" form:"mail" binding:"required"`
	Attachments  []*multipart.FileHeader `json:"attachment,omitempty" form:"attachments" binding:"required"` // change form to "attachments[]" take no effect also.
}

func Mail(c *gin.Context) {
	var postData MailUpload
	err := c.Bind(&postData)
	if err != nil {
		fmt.Println(err)
		c.String(http.StatusBadRequest, err.Error())
	} else {
		fmt.Printf("%#v\n", postData)
		c.String(http.StatusOK, "ok")
	}
}
```

request send command by curl:
```bash
curl -v -H "Content-Type:multipart/form-data" -X POST http://localhost:8080/api/latest/newmail -F "attachments[]=@./2019-5-1_day_trends.png" -F mail=123
```

my error: `Key: 'MailUpload.Attachments' Error:Field validation for 'Attachments' failed on the 'required' tag`

### PR DESCRIPTION
**Pull request by vkd**
Fix #1878
Add support multi files on bind multipart requests.

Example:
```
type s struct {
	Files []*multipart.FileHeader `form:"files"`
}
```

### CODE REVIEW

File: binding/form_test.go [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+	"bytes"
+	"io/ioutil"
+	"mime/multipart"
+	"net/http"
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+)
+
+func Test_formMultipartBinding_Bind_OneFile(t *testing.T) {
```
Comment (thinkerou) [inline binding/form_test.go]: please use `TestFormMul...` style.

File: binding/form_test.go [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+	assertMultipartFileHeader(t, s.FilePtr, file)
+	assert.Len(t, s.SliceValues, 1)
+	assertMultipartFileHeader(t, &s.SliceValues[0], file)
+	assert.Len(t, s.SlicePtrs, 1)
+	assertMultipartFileHeader(t, s.SlicePtrs[0], file)
+	assertMultipartFileHeader(t, &s.ArrayValues[0], file)
+	assertMultipartFileHeader(t, s.ArrayPtrs[0], file)
+}
+
+func Test_formMultipartBinding_Bind_TwoFiles(t *testing.T) {
```
Comment (thinkerou) [inline binding/form_test.go]: please use `TestFormMultipart...` style.

File: binding/form.go [hunk 3]
```diff
@@ -68,22 +69,54 @@ type multipartRequest http.Request
...
-		if err != nil {
-			return false, err
+	if files := r.MultipartForm.File[key]; len(files) != 0 {
+		return setByMultipartFormFile(value, field, files)
+	}
+
+	return setByForm(value, field, r.MultipartForm.Value, key, opt)
+}
+
+var errMultipartUnsupportedFieldType = errors.New("unsupported field type for multipart.FileHeader")
```
Comment (thinkerou) [inline binding/form.go]: maybe we should not use global var, do you think?

File: binding/form.go [hunk 4]
```diff
@@ -68,22 +69,54 @@ type multipartRequest http.Request
```
Comment (thinkerou) [inline binding/form.go]: @vkd can move `multipartRequest` code to `form_mapping.go`? thanks!

Comment (vkd) [reply binding/form.go]: I agree with you about moving this code from `form.go` file, but I think `form_mapping.go` is not good place for that.
I prefer to move this code to new file like `multipart_form_mapping.go`. What do you think?

Comment (thinkerou) [reply binding/form.go]: @vkd OK

**Comment by vkd** [comment]
Fixed

File: binding/multipart_form_mapping_test.go [hunk 5]
```diff
@@ -39,7 +39,7 @@ func Test_formMultipartBinding_Bind_OneFile(t *testing.T) {
 	assertMultipartFileHeader(t, s.ArrayPtrs[0], file)
 }
 
-func Test_formMultipartBinding_Bind_TwoFiles(t *testing.T) {
+func TestFormMultipartBinding_Bind_TwoFiles(t *testing.T) {
```
Comment (thinkerou) [inline binding/multipart_form_mapping_test.go]: please use `TestFormMultipartBindingBindTwoFiles`.

File: binding/multipart_form_mapping_test.go [hunk 6]
```diff
@@ -68,7 +68,7 @@ func Test_formMultipartBinding_Bind_TwoFiles(t *testing.T) {
 	}
 }
 
-func Test_formMultipartBinding_Bind_Error(t *testing.T) {
+func TestFormMultipartBinding_Bind_Error(t *testing.T) {
```
Comment (thinkerou) [inline binding/multipart_form_mapping_test.go]: please use `TestFormMultipartBindingBindError`

File: binding/multipart_form_mapping.go [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+package binding
+
+import (
+	"errors"
+	"mime/multipart"
+	"net/http"
+	"reflect"
+)
+
+type multipartRequestSetter http.Request
```
Comment (thinkerou) [inline binding/multipart_form_mapping.go]: usually, `...er` or `...or` is interface.

Comment (vkd) [reply binding/multipart_form_mapping.go]: You are right! Usually..., but not always, example: [nopCloser](https://golang.org/src/io/ioutil/ioutil.go?s=3278:3299#L110)

In my case `multipartRequestSetter` is a wrapper for the `http.Request` over the `setter` interface, and previous name (`multipartRequest`) said nothing about why it wrapped.

I know about a naming of interfaces, but in this case I don't know a better name. Maybe you can suggest something for that struct?

Comment (thinkerou) [reply binding/multipart_form_mapping.go]: thanks, but I think `multipartRequest` is better. and waiting @appleboy review the pull request.

**Comment by appleboy** [comment]
@vkd Can you also add an example in `README.md`?

**Comment by vkd** [comment]
I've updated the `README.md` the [Multipart/Urlencoded binding](https://github.com/gin-gonic/gin#multiparturlencoded-binding) part.
